## Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

### Additional Exercise

In [1]:
import torch
print(f"{torch.__version__}")

2.1.2+cu118


Q2.  ANSWER

In [2]:
random_tensor = torch.rand((7, 7))

print(random_tensor)

tensor([[0.2234, 0.2842, 0.8989, 0.9920, 0.6975, 0.5905, 0.4453],
        [0.7946, 0.1625, 0.4610, 0.5140, 0.6554, 0.7686, 0.3572],
        [0.3476, 0.0050, 0.1635, 0.3963, 0.5519, 0.1904, 0.3504],
        [0.2869, 0.9863, 0.3215, 0.6834, 0.8017, 0.0596, 0.8793],
        [0.2539, 0.1186, 0.8208, 0.5416, 0.3667, 0.8620, 0.1467],
        [0.9057, 0.9503, 0.2164, 0.0461, 0.6786, 0.4177, 0.7850],
        [0.3221, 0.2321, 0.0090, 0.2438, 0.2438, 0.6170, 0.3502]])


Q3 ANSWER

In [5]:
random_tensor_1 = torch.rand((7, 7))

# Create the second random tensor with shape (1, 7)
random_tensor_2 = torch.rand((1, 7))

# Transpose the second tensor
random_tensor_2_transposed = random_tensor_2.t()
result_tensor = torch.mm(random_tensor_1, random_tensor_2_transposed)

print(result_tensor)

tensor([[0.8623],
        [1.4384],
        [1.3755],
        [1.7888],
        [0.9928],
        [1.3711],
        [1.6429]])


Q4 ANSWER

In [7]:
torch.manual_seed(0)

# Create a random tensor with shape (7, 7)
random_tensor = torch.rand((7, 7))

print(random_tensor)
import torch

# Set a seed for reproducibility
torch.manual_seed(42)

# Create a random tensor with shape (7, 7) in PyTorch
tensor_7x7 = torch.rand(7, 7)

# Create a random tensor with shape (1, 7) in PyTorch
tensor_1x7 = torch.rand(1, 7)

# Transpose the second tensor
tensor_1x7_transposed = tensor_1x7.t()

# Perform matrix multiplication
result = torch.mm(tensor_7x7, tensor_1x7_transposed)

print("Random Tensor (7x7):\n", tensor_7x7)
print("\nRandom Tensor (1x7, transposed):\n", tensor_1x7_transposed)
print("\nResult of Matrix Multiplication:\n", result)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Random Tensor (7x7):
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

Random Tensor (1x7, transposed):
 tensor([[0.1952],

Q5 ANSWER

Yes, PyTorch provides a GPU equivalent for setting the random seed. You can use torch.cuda.manual_seed to set the random seed for GPU operations

In [8]:
torch.manual_seed(1234)

# Check if a GPU is available
if torch.cuda.is_available():
    #  GPU random seed
    torch.cuda.manual_seed(1234)

c:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 8000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


Q6 ANSWER

In [12]:
torch.manual_seed(1234)

# Check if a GPU is available
if torch.cuda.is_available():
    # Set the random seed for GPU operations (optional)
    torch.cuda.manual_seed(5678)  

    # Create random tensors on the GPU
    tensor_gpu_1 = torch.rand((2, 3), device="cuda")
    tensor_gpu_2 = torch.rand((2, 3), device="cuda")

    print("Random Tensor 1 (GPU):\n", tensor_gpu_1)
    print("\nRandom Tensor 2 (GPU):\n", tensor_gpu_2)
else:
    print("GPU not available. Please ensure that PyTorch is configured to use GPU.")

GPU not available. Please ensure that PyTorch is configured to use GPU.


Q7. ANSWER

In [13]:
torch.manual_seed(1234)

# Check if a GPU is available
if torch.cuda.is_available():
    # Set the random seed for GPU operations (optional)
    torch.cuda.manual_seed(5678) 

    # Create random tensors on the GPU
    tensor_gpu_1 = torch.rand((2, 3), device="cuda")
    tensor_gpu_2 = torch.rand((3, 2), device="cuda")  

    # Perform matrix multiplication
    result_gpu = torch.mm(tensor_gpu_1, tensor_gpu_2)

    print("Random Tensor 1 (GPU):\n", tensor_gpu_1)
    print("\nRandom Tensor 2 (GPU):\n", tensor_gpu_2)
    print("\nResult of Matrix Multiplication (GPU):\n", result_gpu)
else:
    print("GPU not available. Please ensure that PyTorch is configured to use GPU.")

GPU not available. Please ensure that PyTorch is configured to use GPU.


Q8.

In [14]:

torch.manual_seed(1234)

# Check if a GPU is available
if torch.cuda.is_available():
    # Set the random seed for GPU operations (optional)
    torch.cuda.manual_seed(5678)  

    # Create random tensors on the GPU
    tensor_gpu_1 = torch.rand((2, 3), device="cuda")
    tensor_gpu_2 = torch.rand((3, 2), device="cuda")  

    # Perform matrix multiplication
    result_gpu = torch.mm(tensor_gpu_1, tensor_gpu_2)

    print("Result of Matrix Multiplication (GPU):\n", result_gpu)

    # Find the maximum and minimum values
    max_value = torch.max(result_gpu)
    min_value = torch.min(result_gpu)

    print("\nMaximum Value:", max_value.item())
    print("Minimum Value:", min_value.item())
else:
    print("GPU not available. Please ensure that PyTorch is configured to use GPU.")

GPU not available. Please ensure that PyTorch is configured to use GPU.


Q9.

In [15]:
torch.manual_seed(1234)

# Check if a GPU is available
if torch.cuda.is_available():

    torch.cuda.manual_seed(5678)  
    # Create random tensors on the GPU
    tensor_gpu_1 = torch.rand((2, 3), device="cuda")
    tensor_gpu_2 = torch.rand((3, 2), device="cuda") 

    # Perform matrix multiplication
    result_gpu = torch.mm(tensor_gpu_1, tensor_gpu_2)

    print("Result of Matrix Multiplication (GPU):\n", result_gpu)

    # Find the indices of the maximum and minimum values
    max_index = torch.argmax(result_gpu)
    min_index = torch.argmin(result_gpu)

    # Convert flat index to 2D indices
    max_index_2d = torch.unravel_index(max_index, result_gpu.shape)
    min_index_2d = torch.unravel_index(min_index, result_gpu.shape)

    print("\nIndices of Maximum Value:", max_index_2d)
    print("Indices of Minimum Value:", min_index_2d)
else:
    print("GPU not available. Please ensure that PyTorch is configured to use GPU.")

GPU not available. Please ensure that PyTorch is configured to use GPU.


Q10

In [16]:

torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor_with_dimensions = torch.rand((1, 1, 1, 10))

# Remove singleton dimensions to get a tensor with shape (10)
tensor_without_dimensions = tensor_with_dimensions.squeeze()

# Print the first tensor and its shape
print("Original Tensor with Dimensions:\n", tensor_with_dimensions)
print("Shape of Original Tensor:", tensor_with_dimensions.shape)

# Print the second tensor and its shape
print("\nTensor without Dimensions:\n", tensor_without_dimensions)
print("Shape of Tensor without Dimensions:", tensor_without_dimensions.shape)


Original Tensor with Dimensions:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of Original Tensor: torch.Size([1, 1, 1, 10])

Tensor without Dimensions:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of Tensor without Dimensions: torch.Size([10])
